/// A response candidate generated from the model.
public struct Candidate: Codable {

	/// Output only. Generated content returned from the model.
	public var content: Content

	/// Optional. Output only. The reason why the model stopped generating tokens.
	/// If empty, the model has not stopped generating tokens.
	public var finishReason: FinishReason?

	/// List of ratings for the safety of a response candidate.
	/// There is at most one rating per category.
	public var safetyRatings: [SafetyRating]

	/// Output only. Citation information for model-generated candidate.
	/// This field may be populated with recitation information for any text included in the content. These are passages that are "recited" from copyrighted material in the foundational LLM's training data.
	public var citationMetadata: CitationMetadata

	/// Output only. Token count for this candidate.
	public var tokenCount: Int

	/// Output only. Attribution information for sources that contributed to a grounded answer.
	/// This field is populated for `GenerateAnswer` calls.
	public var groundingAttributions: [GroundingAttribution]

	/// Output only. Grounding metadata for the candidate.
	/// This field is populated for `GenerateContent` calls.
	public var groundingMetadata: GroundingMetadata?

	/// Output only. Average log probability score of the candidate.
	public var avgLogprobs: Double

	/// Output only. Log-likelihood scores for the response tokens and top tokens
	public var logprobsResult: LogprobsResult

	/// Output only. Metadata related to url context retrieval tool.
	public var urlContextMetadata: UrlContextMetadata

	/// Output only. Index of the candidate in the list of response candidates.
	public var index: Int

	/// Optional. Output only. Details the reason why the model stopped generating tokens. This is populated only when `finishReason` is set.
	public var finishMessage: String?

	/// Defines the reason why the model stopped generating tokens.
	public enum FinishReason: String, Codable {

		/// Default value. This value is unused.
		case unspecified = "FINISH_REASON_UNSPECIFIED"

		/// Natural stop point of the model or provided stop sequence.
		case stop = "STOP"

		/// The maximum number of tokens as specified in the request was reached.
		case maxTokens = "MAX_TOKENS"

		/// The response candidate content was flagged for safety reasons.
		case safety = "SAFETY"

		/// The response candidate content was flagged for recitation reasons.
		case recitation = "RECITATION"

		/// The response candidate content was flagged for using an unsupported language.
		case language = "LANGUAGE"

		/// Unknown reason.
		case other = "OTHER"

		/// Token generation stopped because the content contains forbidden terms.
		case blocklist = "BLOCKLIST"

		/// Token generation stopped for potentially containing prohibited content.
		case prohibitedContent = "PROHIBITED_CONTENT"

		/// Token generation stopped because the content potentially contains Sensitive Personally Identifiable Information (SPII).
		case spii = "SPII"

		/// The function call generated by the model is invalid.
		case malformedFunctionCall = "MALFORMED_FUNCTION_CALL"

		/// Token generation stopped because generated images contain safety violations.
		case imageSafety = "IMAGE_SAFETY"

		/// Image generation stopped because generated images has other prohibited content.
		case imageProhibitedContent = "IMAGE_PROHIBITED_CONTENT"

		/// Image generation stopped because of other miscellaneous issue.
		case imageOther = "IMAGE_OTHER"

		/// The model was expected to generate an image, but none was generated.
		case noImage = "NO_IMAGE"

		/// Image generation stopped due to recitation.
		case imageRecitation = "IMAGE_RECITATION"

		/// Model generated a tool call but no tools were enabled in the request.
		case unexpectedToolCall = "UNEXPECTED_TOOL_CALL"

		/// Model called too many tools consecutively, thus the system exited execution.
		case tooManyToolCalls = "TOO_MANY_TOOL_CALLS"

		/// Request has at least one thought signature missing.
		case missingThoughtSignature = "MISSING_THOUGHT_SIGNATURE"
	}
}
